# --- !Ups

create table RESOURCES (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" VARCHAR NOT NULL,
  "symbol" VARCHAR NOT NULL
);

insert into RESOURCES("name", "symbol") values ('Hydrogenn', 'H');
insert into RESOURCES("name", "symbol") values ('Helium', 'He');

# --- !Downs

drop table RESOURCES if exists;